package ua.gexlq.TelegramStudyBot.process.callbackQuery.enums;

public enum CallBackDataTypes {
	// CALL_BACK_DATA CODES

	// CALLBACKDATA FROM WORK MENU (REGISTRATION)
	SET_USER_FACULTY_TO("[SET_USER_FACULTY_TO]"), SET_USER_SPECIALIZATION_TO("[SET_USER_SPECIALIZATION_TO]"),
	SET_USER_SEMESTER_TO("[SET_USER_SEMESTER_TO]"),

	// CALLBACKDATA FROM SETTINGS MENU
	CHANGE_FACULTY("[CHANGE_FACULTY]"), CHANGE_SPECIALIZATION("[CHANGE_SPECIALIZATION]"),
	CHANGE_SEMESTER("[CHANGE_SEMESTER]"), CHANGE_USER_LANGUAGE_TO("[CHANGE_USER_LANGUAGE_TO]"),

	// CALLBACKDATA FROM WORK MENU TO PICK WORK
	SELECT_SUBJECT_PAGE("[SELECT_SUBJECT_PAGE]"), SELECT_SUBJECT("[SELECT_SUBJECT]"),
	SELECT_WORK_TYPE("[SELECT_WORK_TYPE]"), SELECT_WORK("[SELECT_WORK]"), SELECT_VARIANT("[SELECT_VARIANT]"),
	
	// CALLBACKDATA FROM WORK MENU TO SELECT OPTION: DOWNLOAD OR UPLOAD FILE
	SELECT_OPTION("[SELECT_OPTION]"),

	// CALLBACKDATA FROM WORK MENU TO RATE WORK BEFORE UPLOAD
	RATE_CONTENT("[RATE_CONTENT]"), RATE_IMPLEMENTATION("[RATE_IMPLEMENTATION]"), RATE_MARK("[RATE_MARK]"),

	// CALLBACKDATA FROM UPLOAD AND DOWNLOAD MENUES
	UPLOAD("[UPLOAD]"), UPLOAD_FILE("[UPLOAD_FILE]"), UPLOAD_RULES("[UPLOAD_RULES]"),
	DOWNLOAD("[DOWNLOAD]"), DOWNLOAD_FILE("[DOWNLOAD_FILE]"), DOWNLOAD_SOFTWARE("[DOWNLOAD_SOFTWARE]"),

	ERROR("[ERROR]"),

	GO_NEXT_TO("[GO_NEXT_TO]"), GO_BACK_TO("[GO_BACK_TO]");

	private final String callBackData;

	CallBackDataTypes(String callBackData) {
		this.callBackData = callBackData;
	}

	@Override
	public String toString() {
		return callBackData;
	}
}
